apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-STAGING_SANDBOX_ID
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/pipelineRunner: glob:refs-pull-285-merge-*-pipeline-runner
  labels:
    sandboxId: STAGING_SANDBOX_ID
spec:
  releaseName: pipeline
  chart:
    git: https://github.com/hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: STAGING_CHART_REF
  valuesFrom:
    - configMapKeyRef:
        name: account-config
        namespace: flux
        key: account-config.yaml
  values:
    clusterEnv: staging
    pipelineRunner:
      image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/pipeline:refs-pull-285-merge-b125469cc25fd73d94ad51175b17f23b2bd22157-pipeline-runner
    sandboxId: STAGING_SANDBOX_ID
    memoryRequest: 29Gi
    replicaCount: 0
    serviceAccount:
      iamRole: pipeline-role-staging
