apiVersion: v1
kind: Namespace
metadata:
  name: ui-alex-add-sce
  labels:
    sandboxId: alex-add-sce
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ui-chart
  namespace: ui-alex-add-sce
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/iac
  ref:
    branch: master
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ui
  namespace: ui-alex-add-sce
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/ui
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ui
  namespace: ui-alex-add-sce
spec:
  imageRepositoryRef:
    name: ui
    namespace: ui-alex-add-sce
  filterTags:
    pattern: ^refs-pull-1000-merge-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: ui-image-update
  namespace: ui-alex-add-sce
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - UI image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ui
  namespace: ui-alex-add-sce
  labels:
    sandboxId: alex-add-sce
spec:
  releaseName: ui
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: ui-chart
        namespace: ui-alex-add-sce
      reconcileStrategy: Revision
  values:
    # disable readiness probes as load balancer performs
    # its own health checks/cordoning
    readinessProbe:
      probeType: exec
      command: [echo, '0']
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    livenessProbe:
      probeType: tcpSocket
    service:
      additionalHosts: false
    kubernetes:
      env: staging
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: alex-add-sce
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: ui
      tag: refs-pull-1000-merge-de7ddd6011b0dd6bb16ae1a0aca13752fdf3e2d7-1726698499 # {"$imagepolicy": "ui-alex-add-sce:ui:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
    # filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: api-alex-add-sce
  labels:
    sandboxId: alex-add-sce
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: api-chart
  namespace: api-alex-add-sce
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/iac
  ref:
    branch: master
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: api
  namespace: api-alex-add-sce
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/api
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: api
  namespace: api-alex-add-sce
spec:
  imageRepositoryRef:
    name: api
  filterTags:
    pattern: ^refs-pull-527-merge-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: api-image-update
  namespace: api-alex-add-sce
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - API image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api
  namespace: api-alex-add-sce
  labels:
    sandboxId: alex-add-sce
spec:
  releaseName: api
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: api-chart
        namespace: api-alex-add-sce
      reconcileStrategy: Revision
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: /v2/health
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: 100m
    hpa:
      enabled: false
    loadBalancerHealthCheck:
      path: /
    kubernetes:
      env: staging
    biomageCi:
      repo: hms-dbmi-cellenics/api
      sandboxId: alex-add-sce
      rdsSandboxId: default
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: api
      tag: refs-pull-527-merge-65a3e3fdad45a3e9836150136f735b1a9ce6180e-1726786397 # {"$imagepolicy": "api-alex-add-sce:api:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
# filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: worker-alex-add-sce
  labels:
    sandboxId: alex-add-sce
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: worker-chart
  namespace: worker-alex-add-sce
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/worker
  ref:
    commit: 40444f42498b1e99fef5b1ee335b6346c5a4b1d0
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: worker
  namespace: worker-alex-add-sce
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/worker
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: worker-r
  namespace: worker-alex-add-sce
spec:
  imageRepositoryRef:
    name: worker
    namespace: worker-alex-add-sce
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)-r$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: worker-python
  namespace: worker-alex-add-sce
spec:
  imageRepositoryRef:
    name: worker
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)-python$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: worker-image-update
  namespace: worker-alex-add-sce
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Worker image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
  suspend: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-alex-add-sce
  labels:
    sandboxId: alex-add-sce
spec:
  releaseName: worker
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: worker-chart
        namespace: worker-alex-add-sce
      reconcileStrategy: Revision
  values:
    sandboxId: alex-add-sce
    replicaCount: 0
    r:
      image:
        registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
        repository: worker
        tag: refs-heads-master-40444f42498b1e99fef5b1ee335b6346c5a4b1d0-1726251328-r # {"$imagepolicy": "worker-alex-add-sce:worker-r:tag"}
      memoryRequest: 4Gi
    python:
      image:
        registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
        repository: worker
        tag: refs-heads-master-40444f42498b1e99fef5b1ee335b6346c5a4b1d0-1726251328-python # {"$imagepolicy": "worker-alex-add-sce:worker-python:tag"}
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: worker-role-staging
    datadogTags: kube_namespace:worker-alex-add-sce
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-alex-add-sce
  labels:
    sandboxId: alex-add-sce
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pipeline-chart
  namespace: pipeline-alex-add-sce
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/pipeline
  ref:
    branch: add-sce-upload
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: pipeline
  namespace: pipeline-alex-add-sce
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/pipeline
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: pipeline
  namespace: pipeline-alex-add-sce
spec:
  imageRepositoryRef:
    name: pipeline
    namespace: pipeline-alex-add-sce
  filterTags:
    pattern: ^refs-pull-370-merge-[a-f0-9]+-pipeline-runner-(?P<timestamp>[0-9]+)
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: pipeline-image-update
  namespace: pipeline-alex-add-sce
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Pipeline image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-alex-add-sce
  labels:
    sandboxId: alex-add-sce
spec:
  releaseName: pipeline
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: pipeline-chart
        namespace: pipeline-alex-add-sce
      reconcileStrategy: Revision
  values:
    replicaCount: 0
    clusterEnv: staging
    sandboxId: alex-add-sce
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: pipeline
      tag: refs-pull-370-merge-7819c163cf0cb6518958bfdf1b810b2621c2b607-pipeline-runner-1726698957 # {"$imagepolicy": "pipeline-alex-add-sce:pipeline:tag"}
    memoryRequest: 4Gi
    serviceAccount:
      iamRole: pipeline-role-staging
    datadogTags: kube_namespace:pipeline-alex-add-sce
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
