apiVersion: v1
kind: Namespace
metadata:
  name: ui-alex-tchnt556x1t8cdq1r6buw
  labels:
    sandboxId: alex-tchnt556x1t8cdq1r6buw
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ui-chart
  namespace: ui-alex-tchnt556x1t8cdq1r6buw
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/iac
  ref:
    commit: b1e8f2ff249a60b4d7a42126ad342c44b4381075
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ui
  namespace: ui-alex-tchnt556x1t8cdq1r6buw
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/ui
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ui
  namespace: ui-alex-tchnt556x1t8cdq1r6buw
spec:
  imageRepositoryRef:
    name: ui
    namespace: ui-alex-tchnt556x1t8cdq1r6buw
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: ui-image-update
  namespace: ui-alex-tchnt556x1t8cdq1r6buw
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - UI image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
  suspend: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ui
  namespace: ui-alex-tchnt556x1t8cdq1r6buw
  labels:
    sandboxId: alex-tchnt556x1t8cdq1r6buw
spec:
  releaseName: ui
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: ui-chart
        namespace: ui-alex-tchnt556x1t8cdq1r6buw
      reconcileStrategy: Revision
  values:
    # disable readiness probes as load balancer performs
    # its own health checks/cordoning
    readinessProbe:
      probeType: exec
      command: [echo, '0']
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    livenessProbe:
      probeType: tcpSocket
    service:
      additionalHosts: false
    kubernetes:
      env: staging
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: alex-tchnt556x1t8cdq1r6buw
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: ui
      tag: refs-heads-master-f4efa1c30940b48f4e9e6dee378ead10b4bae01e-1732569892 # {"$imagepolicy": "ui-alex-tchnt556x1t8cdq1r6buw:ui:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
      # filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: api-alex-tchnt556x1t8cdq1r6buw
  labels:
    sandboxId: alex-tchnt556x1t8cdq1r6buw
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: api-chart
  namespace: api-alex-tchnt556x1t8cdq1r6buw
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/iac
  ref:
    commit: b1e8f2ff249a60b4d7a42126ad342c44b4381075
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: api
  namespace: api-alex-tchnt556x1t8cdq1r6buw
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/api
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: api
  namespace: api-alex-tchnt556x1t8cdq1r6buw
spec:
  imageRepositoryRef:
    name: api
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: api-image-update
  namespace: api-alex-tchnt556x1t8cdq1r6buw
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - API image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
  suspend: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: api
  namespace: api-alex-tchnt556x1t8cdq1r6buw
  labels:
    sandboxId: alex-tchnt556x1t8cdq1r6buw
spec:
  releaseName: api
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: api-chart
        namespace: api-alex-tchnt556x1t8cdq1r6buw
      reconcileStrategy: Revision
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: /v2/health
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: 100m
    hpa:
      enabled: false
    loadBalancerHealthCheck:
      path: /
    kubernetes:
      env: staging
    biomageCi:
      repo: hms-dbmi-cellenics/api
      sandboxId: alex-tchnt556x1t8cdq1r6buw
      rdsSandboxId: default
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: api
      tag: refs-heads-master-493f75e8a29fe3d8309e356fe3bfef7df9d64074-1732569667 # {"$imagepolicy": "api-alex-tchnt556x1t8cdq1r6buw:api:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
# filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: worker-alex-tchnt556x1t8cdq1r6buw
  labels:
    sandboxId: alex-tchnt556x1t8cdq1r6buw
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: worker-chart
  namespace: worker-alex-tchnt556x1t8cdq1r6buw
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/worker
  ref:
    commit: f6b905afca1a4eaa4b299e3b3d39bd3e7447ab8f
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: worker
  namespace: worker-alex-tchnt556x1t8cdq1r6buw
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/worker
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: worker-r
  namespace: worker-alex-tchnt556x1t8cdq1r6buw
spec:
  imageRepositoryRef:
    name: worker
    namespace: worker-alex-tchnt556x1t8cdq1r6buw
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)-r$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: worker-python
  namespace: worker-alex-tchnt556x1t8cdq1r6buw
spec:
  imageRepositoryRef:
    name: worker
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)-python$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: worker-image-update
  namespace: worker-alex-tchnt556x1t8cdq1r6buw
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Worker image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
  suspend: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-alex-tchnt556x1t8cdq1r6buw
  labels:
    sandboxId: alex-tchnt556x1t8cdq1r6buw
spec:
  releaseName: worker
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: worker-chart
        namespace: worker-alex-tchnt556x1t8cdq1r6buw
      reconcileStrategy: Revision
  values:
    sandboxId: alex-tchnt556x1t8cdq1r6buw
    replicaCount: 0
    r:
      image:
        registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
        repository: worker
        tag: refs-heads-master-f6b905afca1a4eaa4b299e3b3d39bd3e7447ab8f-1732569622-r # {"$imagepolicy": "worker-alex-tchnt556x1t8cdq1r6buw:worker-r:tag"}
      memoryRequest: 4Gi
    python:
      image:
        registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
        repository: worker
        tag: refs-heads-master-f6b905afca1a4eaa4b299e3b3d39bd3e7447ab8f-1732569622-python # {"$imagepolicy": "worker-alex-tchnt556x1t8cdq1r6buw:worker-python:tag"}
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: worker-role-staging
    datadogTags: kube_namespace:worker-alex-tchnt556x1t8cdq1r6buw
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-alex-tchnt556x1t8cdq1r6buw
  labels:
    sandboxId: alex-tchnt556x1t8cdq1r6buw
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pipeline-chart
  namespace: pipeline-alex-tchnt556x1t8cdq1r6buw
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/pipeline
  ref:
    commit: 854c073cef56e5480904f02083959531c3be3d85
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: pipeline
  namespace: pipeline-alex-tchnt556x1t8cdq1r6buw
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/pipeline
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: pipeline
  namespace: pipeline-alex-tchnt556x1t8cdq1r6buw
spec:
  imageRepositoryRef:
    name: pipeline
    namespace: pipeline-alex-tchnt556x1t8cdq1r6buw
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-pipeline-runner-(?P<timestamp>[0-9]+)
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: pipeline-image-update
  namespace: pipeline-alex-tchnt556x1t8cdq1r6buw
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Pipeline image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
  suspend: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-alex-tchnt556x1t8cdq1r6buw
  labels:
    sandboxId: alex-tchnt556x1t8cdq1r6buw
spec:
  releaseName: pipeline
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: pipeline-chart
        namespace: pipeline-alex-tchnt556x1t8cdq1r6buw
      reconcileStrategy: Revision
  values:
    replicaCount: 0
    clusterEnv: staging
    sandboxId: alex-tchnt556x1t8cdq1r6buw
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: pipeline
      tag: refs-heads-master-854c073cef56e5480904f02083959531c3be3d85-pipeline-runner-1732569645 # {"$imagepolicy": "pipeline-alex-tchnt556x1t8cdq1r6buw:pipeline:tag"}
    memoryRequest: 4Gi
    serviceAccount:
      iamRole: pipeline-role-staging
    accountId: '160782110667'
    datadogTags: kube_namespace:pipeline-alex-tchnt556x1t8cdq1r6buw
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
