apiVersion: v1
kind: Namespace
metadata:
  name: ui-alex-ui834-api433-worker30
  labels:
    sandboxId: alex-ui834-api433-worker30
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ui-chart
  namespace: ui-alex-ui834-api433-worker30
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/iac
  ref:
    branch: master
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ui
  namespace: ui-alex-ui834-api433-worker30
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/ui
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ui
  namespace: ui-alex-ui834-api433-worker30
spec:
  imageRepositoryRef:
    name: ui
    namespace: ui-alex-ui834-api433-worker30
  filterTags:
    pattern: ^refs-pull-834-merge-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: ui-image-update
  namespace: ui-alex-ui834-api433-worker30
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - UI image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ui
  namespace: ui-alex-ui834-api433-worker30
  labels:
    sandboxId: alex-ui834-api433-worker30
spec:
  releaseName: ui
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: ui-chart
        namespace: ui-alex-ui834-api433-worker30
      reconcileStrategy: Revision
  values:
    # disable readiness probes as load balancer performs
    # its own health checks/cordoning
    readinessProbe:
      probeType: exec
      command: [echo, '0']
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    livenessProbe:
      probeType: tcpSocket
    service:
      additionalHosts: false
    kubernetes:
      env: staging
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: alex-ui834-api433-worker30
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: ui
      tag: refs-pull-834-merge-2c4a32a499ab68d1c9453a14877bce3cda3a85fd-1684183850 # {"$imagepolicy": "ui-alex-ui834-api433-worker30:ui:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
      # filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: api-alex-ui834-api433-worker30
  labels:
    sandboxId: alex-ui834-api433-worker30
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: api-chart
  namespace: api-alex-ui834-api433-worker30
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/iac
  ref:
    branch: master
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: api
  namespace: api-alex-ui834-api433-worker30
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/api
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: api
  namespace: api-alex-ui834-api433-worker30
spec:
  imageRepositoryRef:
    name: api
  filterTags:
    pattern: ^refs-pull-433-merge-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: api-image-update
  namespace: api-alex-ui834-api433-worker30
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - API image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api
  namespace: api-alex-ui834-api433-worker30
  labels:
    sandboxId: alex-ui834-api433-worker30
spec:
  releaseName: api
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: api-chart
        namespace: api-alex-ui834-api433-worker30
      reconcileStrategy: Revision
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: /v2/health
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: 100m
    hpa:
      enabled: false
    loadBalancerHealthCheck:
      path: /
    kubernetes:
      env: staging
    biomageCi:
      repo: hms-dbmi-cellenics/api
      sandboxId: alex-ui834-api433-worker30
      rdsSandboxId: default
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: api
      tag: refs-pull-433-merge-2666eb740a6845c18167d2b48e0545dc35cbb0ae-1684882442 # {"$imagepolicy": "api-alex-ui834-api433-worker30:api:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
# filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: worker-alex-ui834-api433-worker30
  labels:
    sandboxId: alex-ui834-api433-worker30
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: worker-chart
  namespace: worker-alex-ui834-api433-worker30
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/worker
  ref:
    branch: biomage-changes-4
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: worker
  namespace: worker-alex-ui834-api433-worker30
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/worker
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: worker-r
  namespace: worker-alex-ui834-api433-worker30
spec:
  imageRepositoryRef:
    name: worker
    namespace: worker-alex-ui834-api433-worker30
  filterTags:
    pattern: ^refs-pull-304-merge-[a-f0-9]+-(?P<timestamp>[0-9]+)-r$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: worker-python
  namespace: worker-alex-ui834-api433-worker30
spec:
  imageRepositoryRef:
    name: worker
  filterTags:
    pattern: ^refs-pull-304-merge-[a-f0-9]+-(?P<timestamp>[0-9]+)-python$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: worker-image-update
  namespace: worker-alex-ui834-api433-worker30
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Worker image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-alex-ui834-api433-worker30
  labels:
    sandboxId: alex-ui834-api433-worker30
spec:
  releaseName: worker
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: worker-chart
        namespace: worker-alex-ui834-api433-worker30
      reconcileStrategy: Revision
  values:
    sandboxId: alex-ui834-api433-worker30
    replicaCount: 0
    r:
      image:
        registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
        repository: worker
        tag: refs-pull-304-merge-ad0e078725b0b6f16c552b160251743586e4ce17-1684170421-r # {"$imagepolicy": "worker-alex-ui834-api433-worker30:worker-r:tag"}
      memoryRequest: 4Gi
    python:
      image:
        registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
        repository: worker
        tag: refs-pull-304-merge-ad0e078725b0b6f16c552b160251743586e4ce17-1684170421-python # {"$imagepolicy": "worker-alex-ui834-api433-worker30:worker-python:tag"}
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: worker-role-staging
    datadogTags: kube_namespace:worker-alex-ui834-api433-worker30
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-alex-ui834-api433-worker30
  labels:
    sandboxId: alex-ui834-api433-worker30
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pipeline-chart
  namespace: pipeline-alex-ui834-api433-worker30
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/pipeline
  ref:
    branch: biomage-changes-4
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: pipeline
  namespace: pipeline-alex-ui834-api433-worker30
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/pipeline
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: pipeline
  namespace: pipeline-alex-ui834-api433-worker30
spec:
  imageRepositoryRef:
    name: pipeline
    namespace: pipeline-alex-ui834-api433-worker30
  filterTags:
    pattern: ^refs-pull-302-merge-[a-f0-9]+-pipeline-runner-(?P<timestamp>[0-9]+)
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: pipeline-image-update
  namespace: pipeline-alex-ui834-api433-worker30
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Pipeline image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-alex-ui834-api433-worker30
  labels:
    sandboxId: alex-ui834-api433-worker30
spec:
  releaseName: pipeline
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: pipeline-chart
        namespace: pipeline-alex-ui834-api433-worker30
      reconcileStrategy: Revision
  values:
    replicaCount: 0
    clusterEnv: staging
    sandboxId: alex-ui834-api433-worker30
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: pipeline
      tag: refs-pull-302-merge-764c851eb18f88df8fbad2a1c9c469924a0dfd3b-pipeline-runner-1684182895 # {"$imagepolicy": "pipeline-alex-ui834-api433-worker30:pipeline:tag"}
    memoryRequest: 4Gi
    serviceAccount:
      iamRole: pipeline-role-staging
    datadogTags: kube_namespace:pipeline-alex-ui834-api433-worker30
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
