apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: alex-worker296-pipeline290
  name: ui-alex-worker296-pipeline290
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: alex-worker296-pipeline290
  name: ui
  namespace: ui-alex-worker296-pipeline290
spec:
  chart:
    git: https://github.com/hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: 0088df0cd636bd7a85c7e21da2a14e072852874e
  releaseName: ui
  values:
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: alex-worker296-pipeline290
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: ui
      tag: refs-heads-master-e5ad7931df2b994224de5d7655ffbf706c70e25d
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    readinessProbe:
      command:
      - echo
      - '0'
      probeType: exec
    replicaCount: 1
    service:
      additionalHosts: false
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: alex-worker296-pipeline290
  name: api-alex-worker296-pipeline290
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: alex-worker296-pipeline290
  name: api
  namespace: api-alex-worker296-pipeline290
spec:
  chart:
    git: https://github.com/hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: 0088df0cd636bd7a85c7e21da2a14e072852874e
  releaseName: api
  values:
    biomageCi:
      rdsSandboxId: default
      repo: hms-dbmi-cellenics/api
      sandboxId: alex-worker296-pipeline290
    hpa:
      enabled: false
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: api
      tag: refs-heads-master-6b84c0fe036fee8b256f4b73d2bbed0e8c07fafb
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v2/health
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    readinessProbe:
      path: /v2/health
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: alex-worker296-pipeline290
  name: worker-alex-worker296-pipeline290
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-pull-296-merge-*-python
    filter.fluxcd.io/r: glob:refs-pull-296-merge-*-r
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: alex-worker296-pipeline290
  name: worker
  namespace: worker-alex-worker296-pipeline290
spec:
  chart:
    git: https://github.com/hms-dbmi-cellenics/worker
    path: chart-infra/
    ref: refs/pull/296/head
  releaseName: worker
  values:
    kubernetes:
      env: staging
    python:
      image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/worker:refs-pull-296-merge-a8a2df8e964bdea1619e159d0b1f848e367f7983-python
    r:
      image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/worker:refs-pull-296-merge-a8a2df8e964bdea1619e159d0b1f848e367f7983-r
      memoryRequest: 4Gi
    replicaCount: 0
    sandboxId: alex-worker296-pipeline290
    serviceAccount:
      iamRole: worker-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: alex-worker296-pipeline290
  name: pipeline-alex-worker296-pipeline290
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/pipelineRunner: glob:refs-pull-290-merge-*-pipeline-runner
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: alex-worker296-pipeline290
  name: pipeline
  namespace: pipeline-alex-worker296-pipeline290
spec:
  chart:
    git: https://github.com/hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: refs/pull/290/head
  releaseName: pipeline
  values:
    clusterEnv: staging
    memoryRequest: 4Gi
    pipelineRunner:
      image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/pipeline:refs-pull-290-merge-e2f4f985981b4b06e02942d7f5e47d7d0060b99c-pipeline-runner
    replicaCount: 0
    sandboxId: alex-worker296-pipeline290
    serviceAccount:
      iamRole: pipeline-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
