apiVersion: v1
kind: Namespace
metadata:
  name: ui-alex-pipeline315
  labels:
    sandboxId: alex-pipeline315
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ui-chart
  namespace: ui-alex-pipeline315
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/iac
  ref:
    commit: 6643a45175b7fdac7be9444407b5a21a1ebc63ad
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ui
  namespace: ui-alex-pipeline315
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/ui
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ui
  namespace: ui-alex-pipeline315
spec:
  imageRepositoryRef:
    name: ui
    namespace: ui-alex-pipeline315
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: ui-image-update
  namespace: ui-alex-pipeline315
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - UI image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
  suspend: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ui
  namespace: ui-alex-pipeline315
  labels:
    sandboxId: alex-pipeline315
spec:
  releaseName: ui
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: ui-chart
        namespace: ui-alex-pipeline315
      reconcileStrategy: Revision
  values:
    # disable readiness probes as load balancer performs
    # its own health checks/cordoning
    readinessProbe:
      probeType: exec
      command: [echo, '0']
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    livenessProbe:
      probeType: tcpSocket
    service:
      additionalHosts: false
    kubernetes:
      env: staging
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: alex-pipeline315
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: ui
      tag: refs-heads-master-9c0604be428de80b302b5bb0ee98236326888c20-1692305460 # {"$imagepolicy": "ui-alex-pipeline315:ui:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
    # filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: api-alex-pipeline315
  labels:
    sandboxId: alex-pipeline315
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: api-chart
  namespace: api-alex-pipeline315
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/iac
  ref:
    commit: 6643a45175b7fdac7be9444407b5a21a1ebc63ad
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: api
  namespace: api-alex-pipeline315
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/api
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: api
  namespace: api-alex-pipeline315
spec:
  imageRepositoryRef:
    name: api
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: api-image-update
  namespace: api-alex-pipeline315
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - API image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
  suspend: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api
  namespace: api-alex-pipeline315
  labels:
    sandboxId: alex-pipeline315
spec:
  releaseName: api
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: api-chart
        namespace: api-alex-pipeline315
      reconcileStrategy: Revision
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: /v2/health
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: 100m
    hpa:
      enabled: false
    loadBalancerHealthCheck:
      path: /
    kubernetes:
      env: staging
    biomageCi:
      repo: hms-dbmi-cellenics/api
      sandboxId: alex-pipeline315
      rdsSandboxId: default
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: api
      tag: refs-heads-master-63b336af2289877e4a1d1116ea399414259ad320-1692302612 # {"$imagepolicy": "api-alex-pipeline315:api:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
# filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: worker-alex-pipeline315
  labels:
    sandboxId: alex-pipeline315
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: worker-chart
  namespace: worker-alex-pipeline315
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/worker
  ref:
    commit: c5e4a615c02306c92b1ab3adeb7f7f7163ebf742
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: worker
  namespace: worker-alex-pipeline315
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/worker
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: worker-r
  namespace: worker-alex-pipeline315
spec:
  imageRepositoryRef:
    name: worker
    namespace: worker-alex-pipeline315
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)-r$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: worker-python
  namespace: worker-alex-pipeline315
spec:
  imageRepositoryRef:
    name: worker
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-(?P<timestamp>[0-9]+)-python$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: worker-image-update
  namespace: worker-alex-pipeline315
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Worker image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
  suspend: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-alex-pipeline315
  labels:
    sandboxId: alex-pipeline315
spec:
  releaseName: worker
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: worker-chart
        namespace: worker-alex-pipeline315
      reconcileStrategy: Revision
  values:
    sandboxId: alex-pipeline315
    replicaCount: 0
    r:
      image:
        registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
        repository: worker
        tag: refs-heads-master-c5e4a615c02306c92b1ab3adeb7f7f7163ebf742-1692378987-r # {"$imagepolicy": "worker-alex-pipeline315:worker-r:tag"}
      memoryRequest: 4Gi
    python:
      image:
        registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
        repository: worker
        tag: refs-heads-master-c5e4a615c02306c92b1ab3adeb7f7f7163ebf742-1692378987-python # {"$imagepolicy": "worker-alex-pipeline315:worker-python:tag"}
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: worker-role-staging
    datadogTags: kube_namespace:worker-alex-pipeline315
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-alex-pipeline315
  labels:
    sandboxId: alex-pipeline315
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pipeline-chart
  namespace: pipeline-alex-pipeline315
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/pipeline
  ref:
    branch: improve-seurat
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: pipeline
  namespace: pipeline-alex-pipeline315
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/pipeline
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: pipeline
  namespace: pipeline-alex-pipeline315
spec:
  imageRepositoryRef:
    name: pipeline
    namespace: pipeline-alex-pipeline315
  filterTags:
    pattern: ^refs-pull-315-merge-[a-f0-9]+-pipeline-runner-(?P<timestamp>[0-9]+)
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: pipeline-image-update
  namespace: pipeline-alex-pipeline315
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Pipeline image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-alex-pipeline315
  labels:
    sandboxId: alex-pipeline315
spec:
  releaseName: pipeline
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: pipeline-chart
        namespace: pipeline-alex-pipeline315
      reconcileStrategy: Revision
  values:
    replicaCount: 0
    clusterEnv: staging
    sandboxId: alex-pipeline315
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: pipeline
      tag: refs-pull-315-merge-e4e39eb15a1cc91bde290304cd143391451dea37-pipeline-runner-1692743535 # {"$imagepolicy": "pipeline-alex-pipeline315:pipeline:tag"}
    memoryRequest: 4Gi
    serviceAccount:
      iamRole: pipeline-role-staging
    datadogTags: kube_namespace:pipeline-alex-pipeline315
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
