apiVersion: v1
kind: Namespace
metadata:
  name: api-default
  labels:
    sandboxId: default
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: api
  namespace: api-default
  labels:
    sandboxId: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
spec:
  releaseName: api
  chart:
    git: https://github.com/hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: master
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: "/v2/health"
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: "100m"
    hpa:
      enabled: false
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v2/health
    kubernetes:
      env: staging
    biomageCi:
      repo: hms-dbmi-cellenics/api
      sandboxId: default
      rdsSandboxId: default
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: api
      tag: refs-heads-master-6b84c0fe036fee8b256f4b73d2bbed0e8c07fafb
    replicaCount: 2
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
    - configMapKeyRef:
        name: account-config
        namespace: flux
        key: account-config.yaml
  # filled in by CI. do not modify.
