apiVersion: v1
kind: Namespace
metadata:
  name: ui-changes-3
  labels:
    sandboxId: changes-3
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ui-chart
  namespace: ui-changes-3
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/iac
  ref:
    branch: master
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ui
  namespace: ui-changes-3
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/ui
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ui
  namespace: ui-changes-3
spec:
  imageRepositoryRef:
    name: ui
    namespace: ui-changes-3
  filterTags:
    pattern: ^refs-pull-828-merge-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: ui-image-update
  namespace: ui-changes-3
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - UI image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ui
  namespace: ui-changes-3
  labels:
    sandboxId: changes-3
spec:
  releaseName: ui
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: ui-chart
        namespace: ui-changes-3
      reconcileStrategy: Revision
  values:
    # disable readiness probes as load balancer performs
    # its own health checks/cordoning
    readinessProbe:
      probeType: exec
      command: [echo, '0']
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    livenessProbe:
      probeType: tcpSocket
    service:
      additionalHosts: false
    kubernetes:
      env: staging
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: changes-3
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: ui
      tag: refs-pull-828-merge-b72bcaf30b67d9989c0966d9d2a32a10c692727e-1680024497 # {"$imagepolicy": "ui-changes-3:ui:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
    # filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: api-changes-3
  labels:
    sandboxId: changes-3
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: api-chart
  namespace: api-changes-3
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/iac
  ref:
    branch: master
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: api
  namespace: api-changes-3
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/api
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: api
  namespace: api-changes-3
spec:
  imageRepositoryRef:
    name: api
  filterTags:
    pattern: ^refs-pull-430-merge-[a-f0-9]+-(?P<timestamp>[0-9]+)$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: api-image-update
  namespace: api-changes-3
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - API image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api
  namespace: api-changes-3
  labels:
    sandboxId: changes-3
spec:
  releaseName: api
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: api-chart
        namespace: api-changes-3
      reconcileStrategy: Revision
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: /v2/health
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: 100m
    hpa:
      enabled: false
    loadBalancerHealthCheck:
      path: /
    kubernetes:
      env: staging
    biomageCi:
      repo: hms-dbmi-cellenics/api
      sandboxId: changes-3
      rdsSandboxId: changes-3
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: api
      tag: refs-pull-430-merge-b3c8edd77af442f564eee9aa9eb19a8cd58a0210-1680020066 # {"$imagepolicy": "api-changes-3:api:tag"}
    replicaCount: 1
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - kind: ConfigMap
    name: account-config
    valuesKey: account-config.yaml
    optional: false
# filled in by CI. do not modify.
---
apiVersion: v1
kind: Namespace
metadata:
  name: worker-changes-3
  labels:
    sandboxId: changes-3
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: worker-chart
  namespace: worker-changes-3
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/worker
  ref:
    branch: biomage-changes-3
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: worker
  namespace: worker-changes-3
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/worker
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: worker-r
  namespace: worker-changes-3
spec:
  imageRepositoryRef:
    name: worker
    namespace: worker-changes-3
  filterTags:
    pattern: ^refs-pull-300-merge-[a-f0-9]+-(?P<timestamp>[0-9]+)-r$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: worker-python
  namespace: worker-changes-3
spec:
  imageRepositoryRef:
    name: worker
  filterTags:
    pattern: ^refs-pull-300-merge-[a-f0-9]+-(?P<timestamp>[0-9]+)-python$
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: worker-image-update
  namespace: worker-changes-3
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Worker image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-changes-3
  labels:
    sandboxId: changes-3
spec:
  releaseName: worker
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: worker-chart
        namespace: worker-changes-3
      reconcileStrategy: Revision
  values:
    sandboxId: changes-3
    replicaCount: 0
    r:
      image:
        registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
        repository: worker
        tag: refs-pull-300-merge-d196b086417309ee9273720a88bc8e91bf0e6be9-1679606132-r # {"$imagepolicy": "worker-changes-3:worker-r:tag"}
      memoryRequest: 4Gi
    python:
      image:
        registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
        repository: worker
        tag: refs-pull-300-merge-d196b086417309ee9273720a88bc8e91bf0e6be9-1679606132-python # {"$imagepolicy": "worker-changes-3:worker-python:tag"}
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: worker-role-staging
    datadogTags: kube_namespace:worker-changes-3
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-changes-3
  labels:
    sandboxId: changes-3
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pipeline-chart
  namespace: pipeline-changes-3
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/pipeline
  ref:
    branch: biomage-changes-3
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: pipeline
  namespace: pipeline-changes-3
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/pipeline
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: pipeline
  namespace: pipeline-changes-3
spec:
  imageRepositoryRef:
    name: pipeline
    namespace: pipeline-changes-3
  filterTags:
    pattern: ^refs-pull-300-merge-[a-f0-9]+-pipeline-runner-(?P<timestamp>[0-9]+)
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: pipeline-image-update
  namespace: pipeline-changes-3
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Pipeline image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-changes-3
  labels:
    sandboxId: changes-3
spec:
  releaseName: pipeline
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: pipeline-chart
        namespace: pipeline-changes-3
      reconcileStrategy: Revision
  values:
    replicaCount: 0
    clusterEnv: staging
    sandboxId: changes-3
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: pipeline
      tag: refs-pull-300-merge-87efa638b6ac868606fbd4c4d67c8bc235b28a85-pipeline-runner-1680018926 # {"$imagepolicy": "pipeline-changes-3:pipeline:tag"}
    memoryRequest: 4Gi
    serviceAccount:
      iamRole: pipeline-role-staging
    datadogTags: kube_namespace:pipeline-changes-3
  valuesFrom:
  - kind: ConfigMap
    valuesKey: account-config.yaml
    name: account-config
    optional: false
