---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-default
  labels:
    sandboxId: default
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/pipelineRunner: glob:refs-heads-master-*-pipeline-runner
  labels:
    sandboxId: default
spec:
  releaseName: pipeline
  chart:
    git: https://github.com/hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: 77301d8f1b65371a45811727fa76bedfe2205d45
  valuesFrom:
  - configMapKeyRef:
      name: account-config
      namespace: flux
      key: account-config.yaml
  values:
    clusterEnv: staging
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-master-781dcf61d615f1bac21c8c241cba7180281d21f6-pipeline-runner
    sandboxId: default
    memoryRequest: 29Gi
    replicaCount: 1
    serviceAccount:
      iamRole: pipeline-role-staging
