apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-default
  labels:
    sandboxId: default
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: pipeline-chart
  namespace: pipeline-default
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/pipeline
  ref:
    branch: master
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: pipeline
  namespace: pipeline-default
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/pipeline
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: pipeline
  namespace: pipeline-default
spec:
  imageRepositoryRef:
    name: pipeline
    namespace: pipeline-default
  filterTags:
    pattern: ^refs-heads-master-[a-f0-9]+-pipeline-runner-(?P<timestamp>[0-9]+)
    extract: $timestamp
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: pipeline-image-update
  namespace: pipeline-default
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Pipeline image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-default
  labels:
    sandboxId: default
spec:
  releaseName: pipeline
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: pipeline-chart
        namespace: pipeline-default
      reconcileStrategy: Revision
  values:
    replicaCount: 0
    clusterEnv: staging
    sandboxId: default
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: pipeline
      tag: refs-heads-master-ab93e1b633feaf61221c376912e355fcd6332bf5-pipeline-runner-1708650939 # {"$imagepolicy": "pipeline-default:pipeline:tag"}
    memoryRequest: 16Gi
    serviceAccount:
      iamRole: pipeline-role-staging
    datadogTags: kube_namespace:pipeline-default
  valuesFrom:
    - kind: ConfigMap
      valuesKey: account-config.yaml
      name: account-config
      optional: false
