apiVersion: v1
kind: Namespace
metadata:
  name: api-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: api
  namespace: api-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:refs-pull-411-merge-*
spec:
  releaseName: api
  chart:
    git: https://github.com/hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: STAGING_CHART_REF
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: "/v2/health"
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: "100m"
    hpa:
      enabled: false
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v2/health
    kubernetes:
      env: staging
    biomageCi:
      repo: hms-dbmi-cellenics/api
      sandboxId: STAGING_SANDBOX_ID
      rdsSandboxId: STAGING_RDS_SANDBOX_ID
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: api
      tag: refs-pull-411-merge-28447db20e8d52160278a32192f542a4b0816749
    replicaCount: 1
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
    - configMapKeyRef:
        name: account-config
        namespace: flux
        key: account-config.yaml
  # filled in by CI. do not modify.
