apiVersion: v1
kind: Namespace
metadata:
  name: api-default
  labels:
    sandboxId: default
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: api-chart
  namespace: api-default
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/iac
  ref:
    branch: master
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: api
  namespace: api-default
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/api
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: api
  namespace: api-default
spec:
  imageRepositoryRef:
    name: api
  filterTags:
    pattern: ^(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$
    extract: $version
  policy:
    semver:
      range: '>=0.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: api-image-update
  namespace: api-default
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - API image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./production
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: api
  namespace: api-default
  labels:
    sandboxId: default
spec:
  releaseName: api
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: api-chart
        namespace: api-default
      reconcileStrategy: Revision
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: "/v2/health"
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: "100m"
    hpa:
      enabled: false
    loadBalancerHealthCheck:
      path: "/"
    kubernetes:
      env: production
    biomageCi:
      repo: hms-dbmi-cellenics/api
      sandboxId: default
      rdsSandboxId: default
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: api
      tag: 0.65.1 # {"$imagepolicy": "api-default:api:tag"}
    replicaCount: 4
    serviceAccount:
      iamRole: api-role-production
  valuesFrom:
    - kind: ConfigMap
      name: account-config
      valuesKey: account-config.yaml
      optional: false
# filled in by CI. do not modify.
