apiVersion: v1
kind: Namespace
metadata:
  name: ui-default
  labels:
    sandboxId: default
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: ui-chart
  namespace: ui-default
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/iac
  ref:
    branch: master
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ui
  namespace: ui-default
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/ui
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ui
  namespace: ui-default
spec:
  imageRepositoryRef:
    name: ui
    namespace: ui-default
  filterTags:
    pattern: ^(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$
    extract: $version
  policy:
    semver:
      range: '>=0.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: ui-image-update
  namespace: ui-default
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - UI image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./production
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ui
  namespace: ui-default
  labels:
    sandboxId: default
spec:
  releaseName: ui
  interval: 2m0s
  chart:
    spec:
      chart: charts/nodejs
      sourceRef:
        kind: GitRepository
        name: ui-chart
        namespace: ui-default
      reconcileStrategy: Revision
  values:
    # disable readiness probes as load balancer performs
    # its own health checks/cordoning
    readinessProbe:
      probeType: exec
      command: ['echo', '0']
    loadBalancerHealthCheck:
      path: '/robots.txt'
      periodSeconds: 30
    livenessProbe:
      probeType: tcpSocket
    service:
      additionalHosts: true
    kubernetes:
      env: production
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: default
    image:
      registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
      repository: ui
      tag: "0.64" # {"$imagepolicy": "ui-default:ui:tag"}
    replicaCount: 4
    serviceAccount:
      iamRole: ui-role-production
  valuesFrom:
    - kind: ConfigMap
      name: account-config
      valuesKey: account-config.yaml
      optional: false
      # filled in by CI. do not modify.
