apiVersion: v1
kind: Namespace
metadata:
  name: worker-default
  labels:
    sandboxId: default
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: worker-chart
  namespace: worker-default
spec:
  interval: 5m0s
  url: https://github.com/hms-dbmi-cellenics/worker
  ref:
    commit: d2e010d9a4a3ab06705b0ffa2054b8b1cf34b128
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: worker
  namespace: worker-default
spec:
  image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/worker
  interval: 2m0s
  provider: aws
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: worker-r
  namespace: worker-default
spec:
  imageRepositoryRef:
    name: worker
    namespace: worker-default
  filterTags:
    pattern: ^refs-tags-(?P<version>[0-9]+\.[0-9]+\.[0-9]+)-r$
    extract: $version
  policy:
    semver:
      range: '>=0.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: worker-python
  namespace: worker-default
spec:
  imageRepositoryRef:
    name: worker
  filterTags:
    pattern: ^refs-tags-(?P<version>[0-9]+\.[0-9]+\.[0-9]+)-python$
    extract: $version
  policy:
    semver:
      range: '>=0.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: worker-image-update
  namespace: worker-default
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        name: Flux - Worker image update
        email: ci@biomage.net
  update:
    strategy: Setters
    path: ./production
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-default
  labels:
    sandboxId: default
spec:
  releaseName: worker
  interval: 2m0s
  chart:
    spec:
      chart: chart-infra/
      sourceRef:
        kind: GitRepository
        name: worker-chart
        namespace: worker-default
      reconcileStrategy: Revision
  values:
    sandboxId: default
    replicaCount: 1
    r:
      image:
        registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
        repository: worker
        tag: refs-tags-0.40.0-r # {"$imagepolicy": "worker-default:worker-r:tag"}
      memoryRequest: 44Gi
    python:
      image:
        registry: 160782110667.dkr.ecr.us-east-1.amazonaws.com
        repository: worker
        tag: refs-tags-0.40.0-python # {"$imagepolicy": "worker-default:worker-python:tag"}
    kubernetes:
      env: production
    serviceAccount:
      iamRole: worker-role-production
    datadogTags: kube_namespace:worker-default
  valuesFrom:
    - kind: ConfigMap
      valuesKey: account-config.yaml
      name: account-config
      optional: false
