apiVersion: v1
kind: Namespace
metadata:
  name: worker-default
  labels:
    sandboxId: default
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/r: glob:refs-tags-*-r
    filter.fluxcd.io/python: glob:refs-tags-*-python
  labels:
    sandboxId: default
spec:
  releaseName: worker
  chart:
    git: https://github.com/hms-dbmi-cellenics/worker
    path: chart-infra/
    ref: 5b50767aa2ad80ce8cfb85f936930334bf5f7d23
  valuesFrom:
    - configMapKeyRef:
        name: account-config
        namespace: flux
        key: account-config.yaml
  values:
    kubernetes:
      env: production
    serviceAccount:
      iamRole: worker-role-production
    sandboxId: default
    replicaCount: 2
    r:
      image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/worker:refs-tags-0.28.0-r
      memoryRequest: 28Gi
    python:
      image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/worker:refs-tags-0.28.0-python
