apiVersion: v1
kind: Namespace
metadata:
  name: worker-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: worker
  namespace: worker-STAGING_SANDBOX_ID
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/r: glob:refs-pull-294-merge-*-r
    filter.fluxcd.io/python: glob:refs-pull-294-merge-*-python
  labels:
    sandboxId: STAGING_SANDBOX_ID
spec:
  releaseName: worker
  chart:
    git: https://github.com/hms-dbmi-cellenics/worker
    path: chart-infra/
    ref: STAGING_CHART_REF
  valuesFrom:
    - configMapKeyRef:
        name: account-config
        namespace: flux
        key: account-config.yaml
  values:
    kubernetes:
      env: staging
    serviceAccount:
      iamRole: worker-role-staging
    sandboxId: STAGING_SANDBOX_ID
    replicaCount: 0
    r:
      image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/worker:refs-pull-294-merge-450386ec0f3307368d8cd5be2ed4037dafbbe603-r
      memoryRequest: 28Gi
    python:
      image: 160782110667.dkr.ecr.us-east-1.amazonaws.com/worker:refs-pull-294-merge-450386ec0f3307368d8cd5be2ed4037dafbbe603-python
